### ISSUE TITLE
i become 16x banner

### ISSUE THREAD

**Issue by efor89** [Invy55/SimpleBanner#4]
hi

rly nice plugin, but if I make /banner I get 16 banners!
can you fix this plz?
and can you also make a 24h timer?

**Comment by Invy55** [comment]
What do u mean with a 24h timer? For the number I can add a config

**Comment by Invy55** [comment]
@efor89

**Comment by efor89** [comment]
if a player makes a banner that he can only make a banner again 24hours later

**Comment by efor89** [comment]
so a timer that says when you've made a banner and you want to do it again: you can't make another banner again in 23 hours and 59 minutes and 59 seconds

**Comment by Invy55** [comment]
> so a timer that says when you've made a banner and you want to do it again: you can't make another banner again in 23 hours and 59 minutes and 59 seconds

I will see what I can do

**Comment by efor89** [comment]
thx :)

**Comment by efor89** [comment]
Thank you, it's now the way I wanted it 1banner and a timer <3

**Comment by Invy55** [comment]
I'm happy of how it turned out, just wait for it to publish on poggit, or download manually from [here](https://poggit.pmmp.io/r/97177/SimpleBanner_dev-29.phar)

**Comment by efor89** [comment]
may i translate the plugin
so that the window is displayed in german?

just want it for my server.

**Comment by Invy55** [comment]
> may i translate the plugin
> so that the window is displayed in german?
> 
> just want it for my server.

Yes of course you can

**Comment by efor89** [comment]
Do you want to have the .phar then so that you also have the German translation?

**Comment by efor89** [comment]
Would you like to have the .phar so that you also have the German translation?

**Comment by Invy55** [comment]
> Do you want to have the .phar then so that you also have the German translation?

If you want you can fork the project and traslate it in your fork so then I can add it as a version

**Comment by efor89** [comment]
This is the first plugin I have translated. I'm still a noob in something like that. I'd rather I just give you the .phar ^^

**Comment by efor89** [comment]
but the translation is good

**Comment by Invy55** [comment]
Ok then upload it somewhere and send me

**Comment by efor89** [comment]
have you discord?

**Comment by Invy55** [comment]
Yes, Invy55#7131
