### ISSUE TITLE
Doest Work!

### ISSUE THREAD

**Issue by MonoAdrian23** [Invy55/SimpleBanner#5]
You can create a Banner but this is a normal Banner
Pocketmine 3.15.0
Simplebanner Dev 27

**Comment by Invy55** [comment]
Do you still need help?

**Comment by MonoAdrian23** [comment]
No thanks but i have a little question.
Can you add German language for this Plugin?

**Comment by Invy55** [comment]
Yes going to add languages soon

**Comment by MonoAdrian23** [comment]
Thank you very much this Plugin is great
