### ISSUE TITLE
Language?

### ISSUE THREAD

**Issue by MonoAdrian23** [Invy55/SimpleBanner#7]
Hey Invy, thanks for you're hard Work at this Plugin.
Since the latest Update you have add languages but when i Install this Plugin its only a empty english file in the folder.
I use Simplebanner Dev 34 and Pocketmine 3.15.1
Thanks you very much!

**Comment by Invy55** [comment]
> Hey Invy, thanks for you're hard Work at this Plugin.
> Since the latest Update you have add languages but when i Install this Plugin its only a empty english file in the folder.
> I use Simplebanner Dev 34 and Pocketmine 3.15.1
> Thanks you very much!

Wait you upgraded form the last version? In this case I can't do much because as far as I know the plugin can't download data from itself so you have 2 ways: you copy them by hand or you remove the folder and it gets recreated with all the files

**Comment by MonoAdrian23** [comment]
OK i try this way.
Thank you very much

**Comment by MonoAdrian23** [comment]
I have delete all.
But it doesnt create the german file.

**Comment by Invy55** [comment]
> I have delete all.
> But it doesnt create the german file.

This is strange
